# Generated by Django 4.0 on 2021-12-29 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_user_avater'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='user_avater',
            new_name='user_avatar',
        ),
    ]
