# Generated by Django 4.0 on 2022-01-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_user_avater_customuser_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_phone_active',
            field=models.BooleanField(default=False, help_text='is user phone_number activated?'),
        ),
    ]
