# Generated by Django 4.0 on 2021-12-29 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0004_basketitem_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basketitem',
            old_name='price',
            new_name='buy_price',
        ),
    ]
