# Generated by Django 4.0 on 2022-01-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0005_rename_price_basketitem_buy_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='basket',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
