# Generated by Django 4.0 on 2022-01-15 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0006_basket_created_on_basket_updated_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='basketitem',
            options={'ordering': ['basket']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='producttag',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='storetype',
            options={'ordering': ['title']},
        ),
    ]
